panel_iframe:
  portainer:
    title: Portainer
    url: "http://172.17.0.1:9000/#/containers"
    icon: mdi:docker
    require_admin: true
  
  duplicati:
    title: Duplicati
    url: "http://172.17.0.1:8200"
    icon: mdi:backup-restore
    require_admin: true

  nodered:
    title: Node Red
    url: "http://172.17.0.1:1880"
    icon: mdi:alpha-n-box

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
