esphome:
  name: drzsn
  friendly_name: drzsn

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fiS7Ok5bi8HJeU56ULvQ0howjWyt3S13vg/F6virokU="

ota:
  password: "397c98186b64259847cddf8feb25c483"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Drzsn Fallback Hotspot"
    password: "5msK132qgjDV"

captive_portal:
    