esphome:
  name: esp32c3-supermini
  friendly_name: esp32C3-supermini

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dzaZ7W9gzxNaIJAkXM61ynoX3PnUGso79AedFThTp4Y="

ota:
  password: "1e604d8de722c71291b8ceb619c05678"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3-Supermini"
    password: "I65QKVWDshTg"

captive_portal:
    