esphome:
  name: esp32-devkitv1

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "espnet"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Devkitv1 Fallback Hotspot"
    password: "54mfPKrzHUKB"

captive_portal:
    
switch:
  - platform: gpio
    name: "Builtin LED"
    pin: 2