esphome:
  name: esp32
  friendly_name: esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aC5A8RmSfmnFhrU2csmxRDHdWgEG2+Z6jUzg0ON3Do4="

ota:
  password: "5a93ed8cb86b041989b8871cf67158ab"

wifi:
  ssid: "espnet"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "d8UyDJyDei7T"

captive_portal:
    
switch:
  - platform: gpio
    name: "Builtin LED"
    pin: 2