esphome:
  name: esp8266
  friendly_name: esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "bNGlScmAnulqzP1fM0jTYBpkKpqKy6orWTtzQxpti98="

ota:
  password: "bbb806899dd689037b34b93974d3a80a"

wifi:
  ssid: "Major"
  password: "12345ABCDE"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "23DBKMbSAJ55"

captive_portal:
    