esphome:
  name: esptest
  friendly_name: esptest

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NHzFqUri9hanzNDwFOFCwSZEUhsSW1JL5I3DIavyZLg="

ota:
  password: "caa7071e2a5c60ee5ee96a6a847e0001"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esptest Fallback Hotspot"
    password: "Tj1h5Xhi5OrK"

captive_portal:
    