esphome:
  name: esp32

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Major"
  password: "12345ABCDE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "ccYbJKxbbMQ2"

captive_portal:
    
switch:
  - platform: gpio
    name: "Builtin LED"
    pin: 2