esphome:
  name: esp32d1mini
  friendly_name: esp32d1mini

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MmuDNxNuCVTFMlHiTV9fW+UD5Fo+xk2+ej8C5HEDe10="

ota:
  password: "1a85c9ec908bc355bd6e95e7da9d7fd6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32D1Mini Fallback Hotspot"
    password: "6BipObaWOjl6"

captive_portal:

switch:
  - platform: gpio
    name: "Builtin LED"
    pin: 2