esphome:
  name: esp8266
  friendly_name: esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cWvfn0LIOS/viuBxAhelQLb6KQyQbVoDLsWy9P+ofFs="

ota:
  password: "eba656aa814843f7196667cf551076a8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "Y3bRgUsIgH7Z"

captive_portal:
    
switch:
- platform: gpio
  name: "Builtin LED"
  pin: 16